Implement Renovate
stackitcloud/stackit-sdk-generator pull request #11
Opened 2023-09-19 15:18 UTC by hcsa73

Removed checksum verification

2023-09-19 16:16 UTC, vicentepinto98 requested changes
I guess it would also make sense to somehow tell explicitly that the generation should be run after this update, because the possible changes/errors should be dealt with directly there and not pop up with the next SDK generation. What about adding `make generate-sdk` as a postUpdateCommand?

2023-09-19 17:10 UTC, hcsa73 commented
> I guess it would also make sense to somehow tell explicitly that the generation should be run after this update, because the possible changes/errors should be dealt with directly there and not pop up with the next SDK generation. What about adding `make generate-sdk` as a postUpdateCommand?

It seems best to add a CI pipeline that generates/lints/tests the SDK, since this is not Renovate-specific

2023-09-19 17:11 UTC, hcsa73 commented on scripts/generate-sdk/generate-sdk.sh
> +GENERATOR_VERSION_NUMBER="${GENERATOR_VERSION:1}"
Capture groups needed for Renovate to work. Will try to simplify them

2023-09-19 17:13 UTC, hcsa73 commented on scripts/generate-sdk/generate-sdk.sh
> -    if [ $(shasum -a 512 ${jar_path} | awk '{print $1;}') != ${GENERATOR_SHASUM_512} ]; then
Requires someone to pull the branch, download the binary, compute the check sum and update the variable. Not sure it's worth it, but could be done

2023-09-20 07:56 UTC, vicentepinto98 commented on scripts/generate-sdk/generate-sdk.sh
> -    if [ $(shasum -a 512 ${jar_path} | awk '{print $1;}') != ${GENERATOR_SHASUM_512} ]; then
How did we get the checksum that is being used currently?

2023-09-20 08:46 UTC, hcsa73 commented on scripts/generate-sdk/generate-sdk.sh
> -    if [ $(shasum -a 512 ${jar_path} | awk '{print $1;}') != ${GENERATOR_SHASUM_512} ]; then
By downloading the binary and computing the checksum locally

2023-09-20 10:02 UTC, vicentepinto98 commented on scripts/generate-sdk/generate-sdk.sh
> -    if [ $(shasum -a 512 ${jar_path} | awk '{print $1;}') != ${GENERATOR_SHASUM_512} ]; then
I thought there was a way to get it from the website. Then this is not that relevant, can be removed

2023-09-20 10:02 UTC, vicentepinto98 submitted a review, later dismissed

2023-09-20 15:25 UTC, vicentepinto98 approved these changes

2023-09-20 15:26 UTC, merged